# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import file_service_pb2 as file__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in file_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadFile = channel.stream_unary(
                '/fileservice.FileService/UploadFile',
                request_serializer=file__service__pb2.FileUploadRequest.SerializeToString,
                response_deserializer=file__service__pb2.FileUploadResponse.FromString,
                _registered_method=True)
        self.DownloadFile = channel.unary_stream(
                '/fileservice.FileService/DownloadFile',
                request_serializer=file__service__pb2.FileDownloadRequest.SerializeToString,
                response_deserializer=file__service__pb2.FileDownloadResponse.FromString,
                _registered_method=True)
        self.ListFiles = channel.unary_unary(
                '/fileservice.FileService/ListFiles',
                request_serializer=file__service__pb2.ListFilesRequest.SerializeToString,
                response_deserializer=file__service__pb2.ListFilesResponse.FromString,
                _registered_method=True)
        self.ReplicateFile = channel.unary_unary(
                '/fileservice.FileService/ReplicateFile',
                request_serializer=file__service__pb2.ReplicateFileRequest.SerializeToString,
                response_deserializer=file__service__pb2.ReplicateFileResponse.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/fileservice.FileService/DeleteFile',
                request_serializer=file__service__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=file__service__pb2.DeleteFileResponse.FromString,
                _registered_method=True)
        self.GetFileInfo = channel.unary_unary(
                '/fileservice.FileService/GetFileInfo',
                request_serializer=file__service__pb2.FileInfoRequest.SerializeToString,
                response_deserializer=file__service__pb2.FileInfoResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadFile(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListFiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFileInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadFile': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadFile,
                    request_deserializer=file__service__pb2.FileUploadRequest.FromString,
                    response_serializer=file__service__pb2.FileUploadResponse.SerializeToString,
            ),
            'DownloadFile': grpc.unary_stream_rpc_method_handler(
                    servicer.DownloadFile,
                    request_deserializer=file__service__pb2.FileDownloadRequest.FromString,
                    response_serializer=file__service__pb2.FileDownloadResponse.SerializeToString,
            ),
            'ListFiles': grpc.unary_unary_rpc_method_handler(
                    servicer.ListFiles,
                    request_deserializer=file__service__pb2.ListFilesRequest.FromString,
                    response_serializer=file__service__pb2.ListFilesResponse.SerializeToString,
            ),
            'ReplicateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateFile,
                    request_deserializer=file__service__pb2.ReplicateFileRequest.FromString,
                    response_serializer=file__service__pb2.ReplicateFileResponse.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=file__service__pb2.DeleteFileRequest.FromString,
                    response_serializer=file__service__pb2.DeleteFileResponse.SerializeToString,
            ),
            'GetFileInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFileInfo,
                    request_deserializer=file__service__pb2.FileInfoRequest.FromString,
                    response_serializer=file__service__pb2.FileInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fileservice.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fileservice.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadFile(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/fileservice.FileService/UploadFile',
            file__service__pb2.FileUploadRequest.SerializeToString,
            file__service__pb2.FileUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fileservice.FileService/DownloadFile',
            file__service__pb2.FileDownloadRequest.SerializeToString,
            file__service__pb2.FileDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListFiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/ListFiles',
            file__service__pb2.ListFilesRequest.SerializeToString,
            file__service__pb2.ListFilesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/ReplicateFile',
            file__service__pb2.ReplicateFileRequest.SerializeToString,
            file__service__pb2.ReplicateFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/DeleteFile',
            file__service__pb2.DeleteFileRequest.SerializeToString,
            file__service__pb2.DeleteFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFileInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fileservice.FileService/GetFileInfo',
            file__service__pb2.FileInfoRequest.SerializeToString,
            file__service__pb2.FileInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
